/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package karaoke;

/**
 *
 * @author Duong Ngo Manh
 */
public class GUIThongTinDatPhong extends javax.swing.JFrame {

    /**
     * Creates new form GUIThongTinPhong
     */
    public GUIThongTinDatPhong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        lblQuanLiThongTinDatPhong = new javax.swing.JLabel();
        pnlThongTinDatPhong = new javax.swing.JPanel();
        lblMaPhong = new javax.swing.JLabel();
        lblTenPhong = new javax.swing.JLabel();
        lblTrangThaiThanhToan = new javax.swing.JLabel();
        lblSoNguoiToiDa = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtSoNguoiToiDa = new javax.swing.JTextField();
        lblLoaiPhong = new javax.swing.JLabel();
        radLoaiVip = new javax.swing.JRadioButton();
        radLoaiThuong = new javax.swing.JRadioButton();
        chkTrangThaiThanhToan = new javax.swing.JCheckBox();
        txtTenPhong = new javax.swing.JTextField();
        pnlChucNangThongTinDatPhong = new javax.swing.JPanel();
        lblTimPhongCNTTDP = new javax.swing.JLabel();
        txtTimPhongCNTTDP = new javax.swing.JTextField();
        btnNhanPhongChoCNTTDP = new javax.swing.JButton();
        btnDatPhongNgayCNTTDP = new javax.swing.JButton();
        btnNhanPhongCho = new javax.swing.JButton();
        btnDatPhongChoCNTTDP = new javax.swing.JButton();
        btnHuyPhongChoCNTTDP = new javax.swing.JButton();
        btnDichVuCNTTDP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachDatPhong = new javax.swing.JTable();
        mnuQuanLiThongTinDatPhong = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniTrangChuCNTTDP = new javax.swing.JMenuItem();
        mniTroGiupCNTTDP = new javax.swing.JMenuItem();
        mniDangXuatCNTTDP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniHoaDonCNTTDP = new javax.swing.JMenuItem();
        mniDichVuCNTTDP = new javax.swing.JMenuItem();
        mniKhuyenMaiCNTTDP = new javax.swing.JMenuItem();
        mniKhachHangCNTTDP = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mniDatPhongCNTTDP = new javax.swing.JMenuItem();
        mniDatPhongChoCNTTDP = new javax.swing.JMenuItem();
        mniThongKe = new javax.swing.JMenu();
        mniThongKeDoanhThuCNTTDP = new javax.swing.JMenuItem();
        mniThongKeDoanhThuTheoKhachHangCNTTDP = new javax.swing.JMenuItem();
        mniThanhToan = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuanLiThongTinDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuanLiThongTinDatPhong.setText("QUẢN LÍ THÔNG TIN ĐẶT PHÒNG");

        pnlThongTinDatPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN ĐẶT PHÒNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        lblMaPhong.setText("Mã phòng:");

        lblTenPhong.setText("Tên phòng:");

        lblTrangThaiThanhToan.setText("Trạng thái thanh toán:");

        lblSoNguoiToiDa.setText("Số người tối đa:");

        txtMaPhong.setText("P001");

        lblLoaiPhong.setText("Loại phòng:");

        radLoaiVip.setText("Vip");
        radLoaiVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLoaiVipActionPerformed(evt);
            }
        });

        radLoaiThuong.setText("Thường");

        chkTrangThaiThanhToan.setText("Đã thanh toán");

        javax.swing.GroupLayout pnlThongTinDatPhongLayout = new javax.swing.GroupLayout(pnlThongTinDatPhong);
        pnlThongTinDatPhong.setLayout(pnlThongTinDatPhongLayout);
        pnlThongTinDatPhongLayout.setHorizontalGroup(
            pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinDatPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenPhong)
                    .addComponent(lblMaPhong)
                    .addComponent(lblSoNguoiToiDa)
                    .addComponent(lblTrangThaiThanhToan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinDatPhongLayout.createSequentialGroup()
                        .addComponent(chkTrangThaiThanhToan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoaiPhong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radLoaiVip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radLoaiThuong)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinDatPhongLayout.createSequentialGroup()
                        .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoNguoiToiDa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(22, 22, 22))))
        );
        pnlThongTinDatPhongLayout.setVerticalGroup(
            pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinDatPhongLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaPhong)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenPhong)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoNguoiToiDa)
                    .addComponent(txtSoNguoiToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThaiThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radLoaiVip)
                    .addComponent(radLoaiThuong)
                    .addComponent(chkTrangThaiThanhToan))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnlChucNangThongTinDatPhong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHỨC NĂNG THÔNG TIN ĐẶT PHÒNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblTimPhongCNTTDP.setText("Tìm phòng (nhập mã)");

        txtTimPhongCNTTDP.setText("P001");
        txtTimPhongCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimPhongCNTTDPActionPerformed(evt);
            }
        });

        btnNhanPhongChoCNTTDP.setText("Nhận phòng chờ");
        btnNhanPhongChoCNTTDP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhanPhongChoCNTTDP.setName(""); // NOI18N
        btnNhanPhongChoCNTTDP.setOpaque(true);
        btnNhanPhongChoCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanPhongChoCNTTDPActionPerformed(evt);
            }
        });

        btnDatPhongNgayCNTTDP.setText("Đặt phòng ngay");
        btnDatPhongNgayCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongNgayCNTTDPActionPerformed(evt);
            }
        });

        btnNhanPhongCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-24.png"))); // NOI18N

        btnDatPhongChoCNTTDP.setText("Đặt phòng chờ");
        btnDatPhongChoCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongChoCNTTDPActionPerformed(evt);
            }
        });

        btnHuyPhongChoCNTTDP.setText("Huỷ phòng chờ");
        btnHuyPhongChoCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyPhongChoCNTTDPActionPerformed(evt);
            }
        });

        btnDichVuCNTTDP.setText("Dịch vụ");
        btnDichVuCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuCNTTDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangThongTinDatPhongLayout = new javax.swing.GroupLayout(pnlChucNangThongTinDatPhong);
        pnlChucNangThongTinDatPhong.setLayout(pnlChucNangThongTinDatPhongLayout);
        pnlChucNangThongTinDatPhongLayout.setHorizontalGroup(
            pnlChucNangThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangThongTinDatPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChucNangThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDatPhongNgayCNTTDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlChucNangThongTinDatPhongLayout.createSequentialGroup()
                        .addComponent(lblTimPhongCNTTDP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimPhongCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNhanPhongCho))
                    .addComponent(btnNhanPhongChoCNTTDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuyPhongChoCNTTDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDichVuCNTTDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDatPhongChoCNTTDP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlChucNangThongTinDatPhongLayout.setVerticalGroup(
            pnlChucNangThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangThongTinDatPhongLayout.createSequentialGroup()
                .addGroup(pnlChucNangThongTinDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNhanPhongCho)
                    .addComponent(txtTimPhongCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimPhongCNTTDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanPhongChoCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDatPhongChoCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDatPhongNgayCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHuyPhongChoCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDichVuCNTTDP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnNhanPhongChoCNTTDP.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH ĐẶT PHÒNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblDanhSachDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phòng", "Số người tối đa", "Loại phòng", "Trạng thái phòng", "Dịch vụ", "Nhân viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachDatPhong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblDanhSachDatPhongFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachDatPhong);
        if (tblDanhSachDatPhong.getColumnModel().getColumnCount() > 0) {
            tblDanhSachDatPhong.getColumnModel().getColumn(0).setMinWidth(30);
            tblDanhSachDatPhong.getColumnModel().getColumn(0).setHeaderValue("STT");
            tblDanhSachDatPhong.getColumnModel().getColumn(1).setHeaderValue("Mã phòng");
            tblDanhSachDatPhong.getColumnModel().getColumn(2).setHeaderValue("Số người tối đa");
            tblDanhSachDatPhong.getColumnModel().getColumn(3).setMinWidth(100);
            tblDanhSachDatPhong.getColumnModel().getColumn(3).setHeaderValue("Loại phòng");
            tblDanhSachDatPhong.getColumnModel().getColumn(4).setMinWidth(130);
            tblDanhSachDatPhong.getColumnModel().getColumn(4).setHeaderValue("Trạng thái phòng");
            tblDanhSachDatPhong.getColumnModel().getColumn(5).setHeaderValue("Dịch vụ");
            tblDanhSachDatPhong.getColumnModel().getColumn(6).setHeaderValue("Nhân viên");
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        jMenu1.setText("Hệ Thống");

        mniTrangChuCNTTDP.setText("Trang chủ");
        jMenu1.add(mniTrangChuCNTTDP);

        mniTroGiupCNTTDP.setText("Trợ giúp");
        mniTroGiupCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTroGiupCNTTDPActionPerformed(evt);
            }
        });
        jMenu1.add(mniTroGiupCNTTDP);

        mniDangXuatCNTTDP.setText("Đăng xuất");
        jMenu1.add(mniDangXuatCNTTDP);

        mnuQuanLiThongTinDatPhong.add(jMenu1);

        jMenu2.setText("Danh Mục");

        mniHoaDonCNTTDP.setText("Hóa đơn");
        jMenu2.add(mniHoaDonCNTTDP);

        mniDichVuCNTTDP.setText("Dịch vụ");
        mniDichVuCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDichVuCNTTDPActionPerformed(evt);
            }
        });
        jMenu2.add(mniDichVuCNTTDP);

        mniKhuyenMaiCNTTDP.setText("Khuyến mãi");
        mniKhuyenMaiCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhuyenMaiCNTTDPActionPerformed(evt);
            }
        });
        jMenu2.add(mniKhuyenMaiCNTTDP);

        mniKhachHangCNTTDP.setText("Khách hàng");
        jMenu2.add(mniKhachHangCNTTDP);

        mnuQuanLiThongTinDatPhong.add(jMenu2);

        jMenu3.setText("Đặt Phòng");

        mniDatPhongCNTTDP.setText("Đặt phòng");
        mniDatPhongCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatPhongCNTTDPActionPerformed(evt);
            }
        });
        jMenu3.add(mniDatPhongCNTTDP);

        mniDatPhongChoCNTTDP.setText("Đặt phòng chờ");
        mniDatPhongChoCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDatPhongChoCNTTDPActionPerformed(evt);
            }
        });
        jMenu3.add(mniDatPhongChoCNTTDP);

        mnuQuanLiThongTinDatPhong.add(jMenu3);

        mniThongKe.setText("Thống Kê");

        mniThongKeDoanhThuCNTTDP.setText("Thống kê doanh thu");
        mniThongKe.add(mniThongKeDoanhThuCNTTDP);

        mniThongKeDoanhThuTheoKhachHangCNTTDP.setText("Thống kê doanh thu theo khách hàng");
        mniThongKeDoanhThuTheoKhachHangCNTTDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeDoanhThuTheoKhachHangCNTTDPActionPerformed(evt);
            }
        });
        mniThongKe.add(mniThongKeDoanhThuTheoKhachHangCNTTDP);

        mnuQuanLiThongTinDatPhong.add(mniThongKe);

        mniThanhToan.setText("Thanh toán");
        mniThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mniThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mniThanhToan.setInheritsPopupMenu(true);
        mnuQuanLiThongTinDatPhong.add(mniThanhToan);

        setJMenuBar(mnuQuanLiThongTinDatPhong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(lblQuanLiThongTinDatPhong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThongTinDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChucNangThongTinDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQuanLiThongTinDatPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlThongTinDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlChucNangThongTinDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniTroGiupCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTroGiupCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniTroGiupCNTTDPActionPerformed

    private void mniDichVuCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDichVuCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDichVuCNTTDPActionPerformed

    private void mniKhuyenMaiCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhuyenMaiCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniKhuyenMaiCNTTDPActionPerformed

    private void mniDatPhongCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatPhongCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDatPhongCNTTDPActionPerformed

    private void mniThongKeDoanhThuTheoKhachHangCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeDoanhThuTheoKhachHangCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniThongKeDoanhThuTheoKhachHangCNTTDPActionPerformed

    private void btnNhanPhongChoCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanPhongChoCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanPhongChoCNTTDPActionPerformed

    private void radLoaiVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLoaiVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radLoaiVipActionPerformed

    private void btnDatPhongChoCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongChoCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatPhongChoCNTTDPActionPerformed

    private void btnDatPhongNgayCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongNgayCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatPhongNgayCNTTDPActionPerformed

    private void btnHuyPhongChoCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyPhongChoCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyPhongChoCNTTDPActionPerformed

    private void btnDichVuCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDichVuCNTTDPActionPerformed

    private void txtTimPhongCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimPhongCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimPhongCNTTDPActionPerformed

    private void tblDanhSachDatPhongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblDanhSachDatPhongFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachDatPhongFocusLost

    private void mniDatPhongChoCNTTDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDatPhongChoCNTTDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniDatPhongChoCNTTDPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIThongTinPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIThongTinPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIThongTinPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIThongTinPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIThongTinPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhongChoCNTTDP;
    private javax.swing.JButton btnDatPhongNgayCNTTDP;
    private javax.swing.JButton btnDichVuCNTTDP;
    private javax.swing.JButton btnHuyPhongChoCNTTDP;
    private javax.swing.JButton btnNhanPhongCho;
    private javax.swing.JButton btnNhanPhongChoCNTTDP;
    private javax.swing.JCheckBox chkTrangThaiThanhToan;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblQuanLiThongTinDatPhong;
    private javax.swing.JLabel lblSoNguoiToiDa;
    private javax.swing.JLabel lblTenPhong;
    private javax.swing.JLabel lblTimPhongCNTTDP;
    private javax.swing.JLabel lblTrangThaiThanhToan;
    private javax.swing.JMenuItem mniDangXuatCNTTDP;
    private javax.swing.JMenuItem mniDatPhongCNTTDP;
    private javax.swing.JMenuItem mniDatPhongChoCNTTDP;
    private javax.swing.JMenuItem mniDichVuCNTTDP;
    private javax.swing.JMenuItem mniHoaDonCNTTDP;
    private javax.swing.JMenuItem mniKhachHangCNTTDP;
    private javax.swing.JMenuItem mniKhuyenMaiCNTTDP;
    private javax.swing.JMenu mniThanhToan;
    private javax.swing.JMenu mniThongKe;
    private javax.swing.JMenuItem mniThongKeDoanhThuCNTTDP;
    private javax.swing.JMenuItem mniThongKeDoanhThuTheoKhachHangCNTTDP;
    private javax.swing.JMenuItem mniTrangChuCNTTDP;
    private javax.swing.JMenuItem mniTroGiupCNTTDP;
    private javax.swing.JMenuBar mnuQuanLiThongTinDatPhong;
    private javax.swing.JPanel pnlChucNangThongTinDatPhong;
    private javax.swing.JPanel pnlThongTinDatPhong;
    private javax.swing.JRadioButton radLoaiThuong;
    private javax.swing.JRadioButton radLoaiVip;
    private javax.swing.JTable tblDanhSachDatPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtSoNguoiToiDa;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTimPhongCNTTDP;
    // End of variables declaration//GEN-END:variables
}
